### PR TITLE
Update DEMO page

### PR DESCRIPTION
**Pull request by informatdcs**
Added some screenshots to demo

### CODE REVIEW

**Comment by JasonLandbridge** [comment]
Thank you so much! Can you add the images as part of this PR? Then it's good to go :+1:

**Comment by informatdcs** [comment]
All done I think, sorry for so many commits, doing it from webpage and its a bit confussing to create a folder

**Review by JasonLandbridge — APPROVED** [review]

**Comment by JasonLandbridge** [comment]
@informatdcs, thank you so much!

**Comment by JasonLandbridge** [comment]
@informatdcs your changes are online: https://www.plexripper.rocks/demo/

**Pull request merged**
